{
    Approvata_da: r.Approvata_da.id,
    Approvata_data: r.Approvata_data,
    Attivo: r.Attivo,
    CIG: r.CIG,
    Capitolo: r.Capitolo.id,
    Commissione_collaudo: r.Commissione_collaudo.id,
    Esercizio: r.Esercizio,
    Importo_tot: r.Importo_tot,
    Liquidaz_data: r.Liquidaz_data,
    Log: r.Log,
    MEPA: r.MEPA,
    Motivo_unicita_fornitore: r.Motivo_unicita_fornitore,
    Nota: r.Nota,
    Ordinata_data: r.Ordinata_data,
    PACWEB: r.PACWEB,
    Processo: r.Processo,
    RUP: r.RUP.id,
    Ricevuta_da: r.Ricevuta_da.id,
    Ricevuta_data: r.Ricevuta_data,
    Richiesta_da: r.Richiesta_da.id,
    Richiesta_data: r.Richiesta_data,
    SGF: r.SGF,
    Scopo: r.Scopo,
    Stato: r.Stato,
    Uffici_destinatari: r.Uffici_destinatari.id,
}


{
"Approvata_da": Dipendenti[0],
"Approvata_data": null,
"Attivo": true,
"CIG": "B55E245667",
"Capitolo": ACapitoli[28],
"Commissione_collaudo": Dipendenti[[]],
"Errori": null,
"Esercizio": 2024,
"HasAllegati": true,
"HasBeni": true,
"Importo_tot": 7445.83,
"Label": "01 €7445.83 - Magaz tecnico: Motoseghe",
"Link2": "https://grist.ge.dipvvf.it/iRL1UtSxehC5/Gestione-Comando-copy/p/64#a1.s337.r5.c1",
"Liquidaz_data": null,
"Log": "2025-01-30 salvatore.dellapepa→Bozza: -\n2025-01-30 salvatore.dellapepa→Inviata: Ordine MEPA residui 2024",
"MD": "\n<center>\n\tMinistero dell'Interno<br>\n  <b>Comando dei vigili del fuoco di Genova</b><br>\n\tUfficio Acquisti<br><br>\n\t<font size=\"4\">\n\t<b>Report acquisto - Modello VF71</b><br>\n\t<font size=\"3\">\n</center><br>\n\nIn data «30.01.2025»,  il dipendente «DELLA PEPA SALVATORE OPER G5 Centrale» **ha richiesto** la fornitura dei seguenti beni/servizi non già disponibili:\n- Uffici destinatari: «Magaz tecnico»;\n- Scopo fornitura: «Motoseghe», eventuale motivo unicità fornitore: «»;\n- Beni/Servizi:\n| Quantità | Bene/Servizio |\n| :---: | :--- |\n| 1.0 | MOTOSEGA STIHL MS194T-3/8 CM. 30 |\n| 1.0 | MOTOSEGA STIHL MS194C-E-3/8 CM. 35 |\n| 1.0 | MOTOSEGA STIHL MS 261C-M-BARRA 45 |\n| 1.0 | ANELLO PIGNONE 325 COMPLETO DI RONDELLA E SIEGER |\n| 1.0 | BARRA 45CM - 325 - 1,3MM+CATENA |\n| 1.0 | CONFEZIONE CANDELA BPMR7A (20PZ) |\n| 1.0 | SET COMPONENTI CATENA 325 - 1,6MM (13PZ) |\n| 1.0 | PUNZONE ROMPI CATENA UNIVERSALE |\n| 1.0 | PUNZONE ROMPI CATENA PICCOLO |\n\t\t\nIn data «None», verificati lo scopo e la disponibilità finanziaria, il responsabile incaricato «None» **ha approvato** l'acquisto.\n\t\t\nIn data «None», verificata sulla piattaforma SGF la **congruità dell'offerta**,  l'Ufficio Acquisti **ha ordinato** la seguente fornitura:\n- RUP: «None»;\n- Importo totale pari a «€ 7445.83» sul capitolo «7325/01 Acquisto mezzi, attrezzature» esercizio «2024»;\n- CIG: «B55E245667», SGF: «38», MEPA: «5032764», PACWEB: «Sì», Commissione di collaudo: «No».\n\nIn data «None» il dipendente «None» ha attestato la **ricezione** della fornitura.\n\n\n\n<center>Il dirigente (firmato digitalmente)</center>\n\n",
"MEPA": "5032764",
"Motivo_unicita_fornitore": "",
"Nota": "Ordine MEPA residui 2024",
"Ordinata_data": null,
"PACWEB": true,
"Processo": "Acquisto",
"RUP": Dipendenti[0],
"Resp_capitolo": Dipendenti[[48,717,61]],
"Resp_capitolo_ids": [48, 717, 61],
"Resp_regolare_esecuzione": Dipendenti[[48,717,61]],
"Ricevuta_da": Dipendenti[0],
"Ricevuta_data": null,
"Richiesta_da": Dipendenti[818],
"Richiesta_data": 2025-01-30T12:38:42.626Z,
"SGF": "38",
"Scopo": "Motoseghe",
"Stato": "Inviata",
"Uffici_destinatari": Uffici[[24]],
"Unselez_beni_ids": [],
"id": 5,
}
